import Head from "next/head";
import CardGrid from "components/CardGrid";
import { cardData3 } from "constants/mock/cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Financial Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="crossOrigin"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="">
        <h1 className="px-10 pt-10 text-left">3 Cards</h1>
        <CardGrid data={cardData3} />
      </main>
    </>
  );
}
