import Head from "next/head";
import CardGrid from "components/CardGrid";
import { cardData3 } from "constants/mock/cards";

export default function Home() {
  return (
    <>
      <Head>
        <title>Financial Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>3 Cards</h1>
        <CardGrid data={cardData3} />
      </main>
    </>
  );
}
